- hosts: local
  connection: local
  become: yes
  become_user: root
  roles:
    - role: "darkwizard242.docker"
      tags: ["docker"]
    - role: "alexinthesky.secure-docker-daemon"
      tags: ["secure-docker"]
      dds_host: 192.168.50.4
      dds_server_cert_path: /etc/default/docker
      dds_restart_docker: no
