Vagrant.configure(2) do |config|
  config.vm.define "vm1" do |vm1|
    vm1.vm.box = "centos/7"
    vm1.disksize.size = '45GB'
    vm1.vm.network "private_network", ip: "192.168.50.4"

    vm1.vm.provider "virtualbox" do |v|
      v.memory = 512
      v.cpus = 1
    end

    vm1.vm.provision "ansible_local" do |ansible|
      ansible.limit = 'all'
      ansible.inventory_path = 'hosts'
      ansible.galaxy_role_file = 'requirements.yml'
      ansible.extra_vars = { ansible_python_interpreter:"/usr/bin/python2" }
      ansible.playbook = 'local.yml'
    end
  end

  config.vm.define "vm2" do |vm2|
    vm2.vm.box = "centos/7"
    vm2.disksize.size = '45GB'
    vm2.vm.network "private_network", ip: "192.168.50.5"

    vm2.vm.provider "virtualbox" do |v|
      v.memory = 512
      v.cpus = 1
    end

    vm2.vm.provision "ansible_local" do |ansible|
      ansible.limit = 'all'
      ansible.inventory_path = 'hosts'
      ansible.galaxy_role_file = 'requirements.yml'
      ansible.extra_vars = { ansible_python_interpreter:"/usr/bin/python2" }
      ansible.playbook = 'local.yml'
    end
  end

end
